name: beyond_ableism
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.1.0
  

  cupertino_icons: ^1.0.2
  
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  connectivity_plus: ^5.0.2
  
  
  # video_player: ^2.8.2

  # state management
  get: ^4.6.6
  get_storage: ^2.1.1
  
  # firebase
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - images/
    - images/onboarding/
    - images/volunteers/
    - images/talents/
    - images/talentMedia/
    # - assets/videos/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #