name: beyond_ableism
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  smooth_page_indicator: ^1.1.0
  get_storage: ^2.1.1

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  connectivity_plus: ^5.0.2
  google_sign_in: ^6.2.1
  # video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - images/
    - images/onboarding/
    # - assets/videos/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #