// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZCM7ZOCMvwa-jbge58GUVSIR1Xg_RN2A',
    appId: '1:869802851631:android:472f57a4195183d74575da',
    messagingSenderId: '869802851631',
    projectId: 'beyondableism',
    storageBucket: 'beyondableism.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpoUYDBevKA0bn4-4Sf2W2pieDix1DMk',
    appId: '1:869802851631:ios:5016ea78889b875f4575da',
    messagingSenderId: '869802851631',
    projectId: 'beyondableism',
    storageBucket: 'beyondableism.appspot.com',
    androidClientId: '869802851631-cclgk9o3r8uvfsm34ssbjsari5p17ijb.apps.googleusercontent.com',
    iosClientId: '869802851631-ui6f8phn0a82g52htbibgttlktgoaa77.apps.googleusercontent.com',
    iosBundleId: 'com.beyondableism.beyondAbleism',
  );
}
